/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package android.support.compat;

public final class R {
    private R() {}

    public static final class attr {
        private attr() {}

        public static final int alpha = 0x7f03002a;
        public static final int font = 0x7f0300dd;
        public static final int fontProviderAuthority = 0x7f0300df;
        public static final int fontProviderCerts = 0x7f0300e0;
        public static final int fontProviderFetchStrategy = 0x7f0300e1;
        public static final int fontProviderFetchTimeout = 0x7f0300e2;
        public static final int fontProviderPackage = 0x7f0300e3;
        public static final int fontProviderQuery = 0x7f0300e4;
        public static final int fontStyle = 0x7f0300e5;
        public static final int fontVariationSettings = 0x7f0300e6;
        public static final int fontWeight = 0x7f0300e7;
        public static final int ttcIndex = 0x7f030211;
    }
    public static final class color {
        private color() {}

        public static final int notification_action_color_filter = 0x7f050083;
        public static final int notification_icon_bg_color = 0x7f050084;
        public static final int ripple_material_light = 0x7f050090;
        public static final int secondary_text_default_material_light = 0x7f050092;
    }
    public static final class dimen {
        private dimen() {}

        public static final int compat_button_inset_horizontal_material = 0x7f0602e2;
        public static final int compat_button_inset_vertical_material = 0x7f0602e3;
        public static final int compat_button_padding_horizontal_material = 0x7f0602e4;
        public static final int compat_button_padding_vertical_material = 0x7f0602e5;
        public static final int compat_control_corner_material = 0x7f0602e6;
        public static final int compat_notification_large_icon_max_height = 0x7f0602e7;
        public static final int compat_notification_large_icon_max_width = 0x7f0602e8;
        public static final int notification_action_icon_size = 0x7f060354;
        public static fina